ALTER TABLE equipment ADD COLUMN IF NOT EXISTS faa_reg_number TEXT NOT NULL DEFAULT '';
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS date_ordered   TEXT NOT NULL DEFAULT '';
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS date_received  TEXT NOT NULL DEFAULT '';
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS group_name     TEXT NOT NULL DEFAULT '';
