pub struct TemplateTask {
    pub id: &'static str,
    pub title: &'static str,
    pub subtasks: &'static [&'static str],
    pub gate: bool,
    pub track_dates: bool,
    pub has_equipment_picker: bool,
    pub has_stakeholders: bool,
}

pub struct TemplatePhase {
    pub id: &'static str,
    pub phase_number: i32,
    pub title: &'static str,
    pub color: &'static str,
    pub description: &'static str,
    pub tasks: &'static [TemplateTask],
}

pub fn get_template() -> &'static [TemplatePhase] {
    &TEMPLATE
}

static TEMPLATE: [TemplatePhase; 4] = [
    // ── Phase 0: Pre-Deal ────────────────────────────────────────────────────────
    TemplatePhase {
        id: "phase-0",
        phase_number: 0,
        title: "Pre-Deal",
        color: "#6B7280",
        description: "Lead comes in, gets triaged at the Monday Sales Sync, and assigned to a Capture person.",
        tasks: &[
            TemplateTask {
                id: "0-0",
                title: "Stage 0 — Lead Intake & Assignment",
                gate: true,
                track_dates: false,
                has_equipment_picker: false,
                has_stakeholders: false,
                subtasks: &[
                    "Lead captured in CRM — source, contact name, company, description of need, date received",
                    "Monday Sales Sync triage — lead reviewed, assigned to BD lane (Core / Growth / Dev Partners), Segment Lead assigns Capture owner",
                    "CRM updated — lead moved from 'Triage' to 'Assigned'; Capture owner, BD lane, and segment recorded",
                    "Capture person notified — knows they own this lead, has the CRM record, knows what to do next (Stage 1)",
                    "EXIT GATE: Lead has a CRM record with source, contact, and description",
                    "EXIT GATE: Capture owner is assigned and notified",
                    "EXIT GATE: BD lane is identified",
                ],
            },
        ],
    },

    // ── Phase A: Capture It ──────────────────────────────────────────────────────
    TemplatePhase {
        id: "phase-a",
        phase_number: 1,
        title: "Phase A — Capture It",
        color: "#D2232A",
        description: "Find the customer, prove we can help, confirm it's worth pursuing. Capture owns Stages 1-3.",
        tasks: &[
            TemplateTask {
                id: "a-1",
                title: "Stage 1 — Identify & Qualify",
                gate: true,
                track_dates: false,
                has_equipment_picker: false,
                has_stakeholders: false,
                subtasks: &[
                    "ICP validation — confirm segment, geography, and industry fit",
                    "Budget confirmed — customer has budget or a funded program that covers our services",
                    "Authority identified — buying decision maker confirmed and engaged",
                    "Need validated — specific security pain point identified",
                    "Timeline understood — when does the customer need a solution; is there urgency?",
                    "Go/No-Go decision — reviewed with Segment Lead",
                    "If drones: regulatory feasibility check (airspace classification, waiver feasibility) — consult Rob Robertson if unclear; kill deal if red",
                    "EXIT GATE: Segment Lead has approved Go/No-Go",
                    "EXIT GATE: ICP fit confirmed (segment, geography, budget, authority, need, timeline)",
                    "EXIT GATE: If drones — regulatory feasibility is green or yellow (not red)",
                    "EXIT GATE: CRM updated with estimated value, key stakeholders, competitive context",
                ],
            },
            TemplateTask {
                id: "a-2",
                title: "Stage 2 — Discover",
                gate: true,
                track_dates: false,
                has_equipment_picker: false,
                has_stakeholders: true,
                subtasks: &[
                    "Stakeholder map — economic buyer, technical buyer, internal champion, procurement, legal; who decides what",
                    "Current state assessment — cameras, SOC, VMS, access control, guard force, alarms in place today",
                    "Requirements gathered — outcomes needed, coverage hours, response times, compliance requirements, SLA expectations",
                    "Budget range validated — surface acceptable price range early to avoid designing a $500K solution for a $100K budget",
                    "Solutions engaged — Solutions is attending discovery meetings and beginning to frame potential approaches",
                    "If drones (P0): site assessment — airspace classification, flight paths, dock placement options, BVLOS determination, network/power availability; consult Rob Robertson (Regulatory) and Eric Larson (Product/Airspace)",
                    "EXIT GATE: Customer problem statement is clear and documented",
                    "EXIT GATE: Requirements are specific enough for Solutions to design against",
                    "EXIT GATE: Budget range is known (at least ballpark)",
                    "EXIT GATE: Solutions person has attended at least one discovery session",
                ],
            },
            TemplateTask {
                id: "a-3",
                title: "Stage 3 — Demo & Validate",
                gate: true,
                track_dates: false,
                has_equipment_picker: false,
                has_stakeholders: false,
                subtasks: &[
                    "Technical demonstration delivered — in-person or virtual; Solutions co-leads the technical portions; address objections directly",
                    "Executive alignment confirmed — economic buyer (the person who writes the check) is bought in before investing in full solution design",
                    "Engagement structure decided — Starter Program (pilot) or direct contract; agreed with customer and Segment Lead",
                    "CRM updated — 25-40% probability; engagement structure recorded",
                    "If Starter Program: define pilot scope — duration (60-90 days), number of sites/docks, success metrics, what conversion to full contract looks like",
                    "HANDOFF to Solutions: provide Discovery Report + engagement structure decision; schedule formal handoff conversation",
                    "EXIT GATE: Customer has seen our capability and objections are addressed",
                    "EXIT GATE: Economic buyer is aligned",
                    "EXIT GATE: Engagement structure agreed (pilot vs. full)",
                    "EXIT GATE: Solutions has the Discovery Report and engagement structure and is ready to design",
                ],
            },
        ],
    },

    // ── Phase B: Build It ────────────────────────────────────────────────────────
    TemplatePhase {
        id: "phase-b",
        phase_number: 2,
        title: "Phase B — Build It",
        color: "#2563EB",
        description: "Design the right solution, price it, write the contract, close. Solutions leads design; Capture leads the close.",
        tasks: &[
            TemplateTask {
                id: "b-4",
                title: "Stage 4 — Design Solution",
                gate: true,
                track_dates: false,
                has_equipment_picker: true,
                has_stakeholders: false,
                subtasks: &[
                    "Solution architecture defined — products (platform, sensors, docks), services (coverage model, SOC, maintenance), operational model (hours, shifts, remote vs. on-site)",
                    "SLA framework defined — response times, uptime, coverage, reporting cadence",
                    "Preliminary pricing check — does this design hit 20%+ margin? If not, adjust architecture now before going further",
                    "Implementation timeline estimated — account for procurement lead times, regulatory timelines, staffing needs",
                    "If standard bundle (Layer 2): map customer requirements to Base/Mid/Elite tier; identify add-ons needed",
                    "If bespoke/Layer 3: engage Solution Architect (Dean Pratt); define custom engineering scope; document integration architecture (VMS, access control, SIEM, APIs); get CFO margin review",
                    "If Starter Program: scope 1-2 docks, single site, 60-90 day window; define success metrics for conversion to full contract",
                    "EXIT GATE: Solution architecture is defined and documented",
                    "EXIT GATE: Preliminary pricing check passed (20%+ margin achievable)",
                    "EXIT GATE: If bespoke — Solution Architect has reviewed and approved the approach",
                    "EXIT GATE: Implementation timeline is realistic given known constraints",
                ],
            },
            TemplateTask {
                id: "b-5",
                title: "Stage 5 — Price, SOW & Approve",
                gate: true,
                track_dates: false,
                has_equipment_picker: false,
                has_stakeholders: false,
                subtasks: &[
                    "Pricing built — from Layer 1 catalog + Layer 2 bundles; apply tier discounts (5/10/15%); calculate all-in monthly cost to customer",
                    "Ops validation — Tyler Bayne confirms component costs are accurate, operationally feasible, capacity available, delivery timeline achievable",
                    "Finance validation — margin meets 20% floor; if not, stop and adjust design or escalate to CFO (Mike Egan)",
                    "SOW drafted — deliverables, SLAs, timeline, roles, payment terms, acceptance criteria",
                    "Contract terms prepared — MSA: liability insurance ($5M+), data privacy, termination, warranty",
                    "Internal approval obtained — Segment Lead reviews; Ops confirms capacity; CRM updated",
                    "If margin below 20% or deal >$500K or non-standard terms or bespoke/Layer 3: CFO (Mike Egan) deal review required",
                    "EXIT GATE: Pricing is built and internally validated (Ops + Finance)",
                    "EXIT GATE: SOW is drafted with all required terms",
                    "EXIT GATE: All required approvals obtained (CFO if needed, executive if >$500K, legal if non-standard)",
                    "EXIT GATE: CRM updated — 50-75% probability",
                ],
            },
            TemplateTask {
                id: "b-6",
                title: "Stage 6 — Propose & Close",
                gate: true,
                track_dates: false,
                has_equipment_picker: false,
                has_stakeholders: true,
                subtasks: &[
                    "Proposal presented — Capture + Solutions co-present; executive summary for C-suite; technical detail for IT/Security",
                    "Objections handled — use references, case studies, competitive positioning; Capture owns price/terms, Solutions owns technical/SLA pushback",
                    "Negotiation completed — track customer approval workflow; target redlines addressed within 1 week",
                    "Contract executed — final signatures; CRM -> 'Closed Won'; billing setup initiated",
                    "Kickoff meeting scheduled — with customer, Delivery, and Solutions",
                    "HANDOFF PACKAGE to Delivery: signed SOW (scope, SLAs, timeline, payment terms)",
                    "HANDOFF PACKAGE: customer contacts — who to call for technical, procurement, and executive issues",
                    "HANDOFF PACKAGE: site details — physical locations, access requirements, infrastructure readiness",
                    "HANDOFF PACKAGE: special conditions — verbal commitments or timeline promises not in the SOW",
                    "HANDOFF PACKAGE: regulatory status — waiver status, licensing status, known timeline risks",
                    "HANDOFF PACKAGE: customer expectations — what matters most; what are they worried about",
                    "EXIT GATE: Contract is signed",
                    "EXIT GATE: Handoff package is complete",
                    "EXIT GATE: Kickoff meeting is scheduled with customer + Delivery + Solutions",
                    "EXIT GATE: CRM -> 'Closed Won'",
                ],
            },
        ],
    },

    // ── Phase C: Run It & Grow It ────────────────────────────────────────────────
    TemplatePhase {
        id: "phase-c",
        phase_number: 3,
        title: "Phase C — Run It & Grow It",
        color: "#16A34A",
        description: "Delivery owns implementation (7-10). Operations runs steady state (11). Capture returns for expansion (12).",
        tasks: &[
            TemplateTask {
                id: "c-7",
                title: "Stage 7 — Procure & Provision",
                gate: true,
                track_dates: true,
                has_equipment_picker: true,
                has_stakeholders: false,
                subtasks: &[
                    "Customer kickoff meeting completed — align on timeline, roles, communication cadence, and customer readiness requirements",
                    "Delivery plan published — milestones, resource allocation, installation schedule, risk register",
                    "Equipment ordered — per SOW hardware profile; vendor lead times confirmed and tracked",
                    "QA & provisioning — receive, inspect, configure, firmware update, stage for deployment",
                    "If drones (P0): FAA waiver application filed — Eric Larson (Product/Airspace) drives filing; Rob Robertson (Regulatory) owns operational narrative; track weekly (expect 4-24 weeks)",
                    "If drones (P0): NDAA/ITAR compliance prepared (if government/defense customer)",
                    "If drones (P1): pilot workforce recruitment initiated — James Nguyen begins recruiting/assigning certified pilots (2-4+ week lead time)",
                    "If manned guarding (P0): state/local guard licensing initiated — business entity registration, guard cards, background checks (2-6 weeks by state)",
                    "If manned guarding (P0): staffing initiated — post orders drafted, shift schedules designed, recruitment started",
                    "EXIT GATE: Equipment ordered and delivery timeline confirmed",
                    "EXIT GATE: Delivery plan published to customer and internal team",
                    "EXIT GATE: All regulatory applications filed (if applicable) with timelines tracked",
                    "EXIT GATE: Customer has confirmed their readiness (project sponsor, team, infrastructure)",
                ],
            },
            TemplateTask {
                id: "c-8",
                title: "Stage 8 — Deploy & Integrate",
                gate: true,
                track_dates: false,
                has_equipment_picker: false,
                has_stakeholders: false,
                subtasks: &[
                    "Equipment installed — docks, network/firewall, LTE/power, sensors, payloads",
                    "System integration completed — VMS, access control, alarms, SOC, SIEM, dispatch (per SOW scope)",
                    "End-to-end testing passed — full system test including failover scenarios",
                    "SOPs created — flight ops, emergency procedures, incident response, maintenance, data handling",
                    "If drones (HARD GATE before Stage 9): FAA waiver approved, state licenses obtained, insurance on file, NDAA/ITAR documented; do NOT proceed to Train & Test until all regulatory approvals are confirmed",
                    "If Layer 3/bespoke: Solution Architect (Dean Pratt) available for integration troubleshooting; custom integration testing protocols; third-party vendor coordination",
                    "EXIT GATE: All equipment installed and configured",
                    "EXIT GATE: All integrations tested and working",
                    "EXIT GATE: SOPs documented",
                    "EXIT GATE: If drones — ALL regulatory approvals confirmed (hard stop)",
                ],
            },
            TemplateTask {
                id: "c-9",
                title: "Stage 9 — Train & Test",
                gate: true,
                track_dates: false,
                has_equipment_picker: false,
                has_stakeholders: false,
                subtasks: &[
                    "Customer training delivered — SOC personnel and security managers trained on system operation and monitoring (Jon Beal runs this)",
                    "User Acceptance Testing (UAT) — flight tests, SLA validation, integration testing; customer participates and signs off",
                    "SOPs and training materials delivered to customer",
                    "If drones (P0): DxD operators certified per Training standards — Training (Jon Beal) owns certification standards",
                    "If drones (P0): pilots deployed — Pilot Workforce (James Nguyen) assigns certified pilots; staffing commitments confirmed",
                    "If BVLOS: Regulatory (Rob Robertson) delivers BVLOS-specific curriculum within Training's framework",
                    "If public sector/DFR: Training (Jon Beal) runs specialized workshop for police/fire chiefs and first responders",
                    "EXIT GATE: All personnel trained and certified (customer and DxD)",
                    "EXIT GATE: UAT completed with documented results",
                    "EXIT GATE: Customer has signed off on system readiness",
                ],
            },
            TemplateTask {
                id: "c-10",
                title: "Stage 10 — Go-Live",
                gate: true,
                track_dates: false,
                has_equipment_picker: false,
                has_stakeholders: true,
                subtasks: &[
                    "Final acceptance testing (FAT) — all criteria verified; punch list resolved",
                    "Written customer acceptance — formal sign-off document obtained",
                    "Billing activated — recurring billing begins per contract terms",
                    "HANDOFF to Operations: complete system configuration documentation",
                    "HANDOFF to Operations: all SOPs (operations, maintenance, emergency, incident response)",
                    "HANDOFF to Operations: customer contacts and escalation paths",
                    "HANDOFF to Operations: known issues, workarounds, and 'watch out for this' notes",
                    "HANDOFF to Operations: maintenance schedule and hardware lifecycle dates",
                    "HANDOFF to Operations: SLA details and reporting requirements",
                    "HANDOFF to Operations: Operations team confirms readiness and signs off on acceptance",
                    "EXIT GATE: Customer has signed acceptance",
                    "EXIT GATE: Billing is activated",
                    "EXIT GATE: Operations has accepted the handoff package and signed off",
                    "EXIT GATE: Solutions is established as ongoing customer concierge",
                ],
            },
            TemplateTask {
                id: "c-11",
                title: "Stage 11 — Operate & Optimize",
                gate: false,
                track_dates: false,
                has_equipment_picker: false,
                has_stakeholders: false,
                subtasks: &[
                    "Service delivered per SLA — monitoring, response, coverage hours as contracted (Operations routes by service type: Jeff Ventrella for remote drone ops, Tyler Bayne for robotic/field hardware)",
                    "Incidents managed — response, resolution, documentation, customer communication",
                    "Monthly operational report delivered to customer",
                    "30-day health check — CSAT survey, KPI review, issue resolution (early warning system)",
                    "Quarterly Business Review (QBR) — Solutions (concierge) joins; review performance, ROI, customer satisfaction, expansion opportunities",
                    "Continuous optimization — patrol routes, false positive reduction, autonomy improvements",
                    "Maintenance and updates — scheduled inspections, firmware/software updates, hardware refresh planning",
                    "Surface expansion opportunities to Solutions — coverage gaps, site growth, contract sizing issues",
                ],
            },
            TemplateTask {
                id: "c-12",
                title: "Stage 12 — Expand & Renew",
                gate: false,
                track_dates: false,
                has_equipment_picker: false,
                has_stakeholders: false,
                subtasks: &[
                    "Expansion opportunities identified — Solutions (concierge) + Ops surface these from QBRs, operational data, and customer conversations",
                    "Renewal process started at 120 days before expiration — 120/90/60-day cadence; performance + ROI summary prepared",
                    "If new capabilities or new sites: loop back to Stage 2 (Discover) — new requirements need new discovery",
                    "If Starter Program -> full contract: loop back to Stage 4 (Design) — redesign at scale using pilot performance data; Capture gathers pilot metrics and Solutions provides narrative",
                    "If simple add-ons (more docks, same site): loop back to Stage 7 (Procure) — design is already known",
                    "If renewal at same scope: stays in Stage 12 — renew and continue",
                    "NRR tracking — target >120% net revenue retention",
                    "Multi-year terms pursued — longer commitments improve predictability and reduce churn risk",
                ],
            },
        ],
    },
];
