pub struct TemplateSubtask {
    pub text: &'static str,
    pub priority: &'static str,   // p0 | p1 | p2 | exit_gate | handoff
    pub condition_key: &'static str, // "" always | "drones" | "manned" | "govdef" | "bespoke" | "starter" | "bvlos" | "!bespoke"
}

pub struct TemplateTask {
    pub id: &'static str,
    pub title: &'static str,
    pub subtasks: &'static [TemplateSubtask],
    pub gate: bool,
    pub track_dates: bool,
    pub has_equipment_picker: bool,
    pub has_stakeholders: bool,
    pub role_tag: &'static str,
    pub stage_number: i32,
}

pub struct TemplatePhase {
    pub id: &'static str,
    pub phase_number: i32,
    pub title: &'static str,
    pub color: &'static str,
    pub description: &'static str,
    pub tasks: &'static [TemplateTask],
}

pub fn get_template() -> &'static [TemplatePhase] {
    &TEMPLATE
}

static TEMPLATE: [TemplatePhase; 3] = [
    // ── Phase A: Capture It ──────────────────────────────────────────────────────
    TemplatePhase {
        id: "phase-a",
        phase_number: 1,
        title: "Phase A — Capture It",
        color: "#D2232A",
        description: "Find the customer, prove we can help, confirm it's worth pursuing. Capture owns Stages 1–3.",
        tasks: &[
            TemplateTask {
                id: "a-1",
                title: "Stage 1 — Identify & Qualify",
                gate: true,
                track_dates: false,
                has_equipment_picker: false,
                has_stakeholders: false,
                role_tag: "capture",
                stage_number: 1,
                subtasks: &[
                    TemplateSubtask { text: "ICP validation — confirm segment, geography, and industry fit", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Budget confirmed — customer has budget or a funded program that covers our services", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Authority identified — buying decision maker confirmed and engaged", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Need validated — specific security pain point identified", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Timeline understood — when does the customer need a solution; is there urgency?", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Go/No-Go decision — reviewed with Segment Lead", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Regulatory feasibility check — airspace classification, waiver feasibility; consult Rob Robertson if unclear; kill deal if red", priority: "p0", condition_key: "drones" },
                    TemplateSubtask { text: "Competitive landscape — what's in place today? Incumbent vendor? Cost of doing nothing?", priority: "p1", condition_key: "" },
                    TemplateSubtask { text: "Internal champion identified — someone inside the customer org who wants this to happen", priority: "p1", condition_key: "" },
                    TemplateSubtask { text: "Initial outreach completed — first contact made; interest confirmed", priority: "p1", condition_key: "" },
                    TemplateSubtask { text: "Manned guarding licensing check — can we license in this jurisdiction? Any unusual state requirements?", priority: "p1", condition_key: "manned" },
                    TemplateSubtask { text: "Gov/defense: budget cycle timing, political will, NDAA/ITAR implications, security clearance requirements", priority: "p1", condition_key: "govdef" },
                    TemplateSubtask { text: "EXIT GATE: Segment Lead has approved Go/No-Go", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: ICP fit confirmed (segment, geography, budget, authority, need, timeline)", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: Regulatory feasibility is green or yellow (not red)", priority: "exit_gate", condition_key: "drones" },
                    TemplateSubtask { text: "EXIT GATE: CRM updated with estimated value, key stakeholders, competitive context", priority: "exit_gate", condition_key: "" },
                ],
            },
            TemplateTask {
                id: "a-2",
                title: "Stage 2 — Discover",
                gate: true,
                track_dates: false,
                has_equipment_picker: false,
                has_stakeholders: true,
                role_tag: "capture",
                stage_number: 2,
                subtasks: &[
                    TemplateSubtask { text: "Stakeholder map — economic buyer, technical buyer, internal champion, procurement, legal; who decides what", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Current state assessment — cameras, SOC, VMS, access control, guard force, alarms in place today", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Requirements gathered — outcomes needed, coverage hours, response times, compliance requirements, SLA expectations", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Budget range validated — surface acceptable price range early; do not let Solutions design a $500K solution for a $100K budget", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Solutions engaged — Solutions is attending discovery meetings and beginning to frame potential approaches", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Site assessment — airspace classification, potential flight paths, dock placement options, BVLOS determination, network/power availability; consult Rob Robertson (Regulatory) and Eric Larson (Airspace)", priority: "p0", condition_key: "drones" },
                    TemplateSubtask { text: "Post assessment — shifts, armed/unarmed, patrol routes, licensing requirements by jurisdiction, staffing estimate", priority: "p0", condition_key: "manned" },
                    TemplateSubtask { text: "Decision-making process mapped — how does this customer buy? Procurement rules? Approval levels? Board involvement?", priority: "p1", condition_key: "" },
                    TemplateSubtask { text: "Customer pain quantified — cost of current problem: false alarms, response times, guard costs, incidents", priority: "p1", condition_key: "" },
                    TemplateSubtask { text: "Document integration requirements early — VMS type, access control system, SIEM, dispatch, third-party platforms", priority: "p1", condition_key: "bespoke" },
                    TemplateSubtask { text: "EXIT GATE: Customer problem statement is clear and documented", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: Requirements are specific enough for Solutions to design against", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: Budget range is known (at least ballpark)", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: Solutions person has attended at least one discovery session", priority: "exit_gate", condition_key: "" },
                ],
            },
            TemplateTask {
                id: "a-3",
                title: "Stage 3 — Demo & Validate",
                gate: true,
                track_dates: false,
                has_equipment_picker: false,
                has_stakeholders: false,
                role_tag: "capture",
                stage_number: 3,
                subtasks: &[
                    TemplateSubtask { text: "Technical demonstration delivered — in-person or virtual; Solutions co-leads the technical portions; address objections directly", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Executive alignment confirmed — economic buyer is bought in before we invest in full solution design", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Engagement structure decided — Starter Program (pilot) or direct contract; agreed with customer and Segment Lead", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "CRM updated — 25–40% probability; engagement structure recorded", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Starter Program scope defined — duration (60–90 days), number of sites/docks, success metrics, what conversion to full contract looks like", priority: "p0", condition_key: "starter" },
                    TemplateSubtask { text: "Reference customers shared — proof points from similar deployments", priority: "p1", condition_key: "" },
                    TemplateSubtask { text: "Competitive positioning addressed — why DxD vs. the alternative (including doing nothing)?", priority: "p1", condition_key: "" },
                    TemplateSubtask { text: "HANDOFF TO SOLUTIONS: confirm they have the Discovery Report — stakeholder map, requirements, budget indication, site details, regulatory status, engagement structure decision", priority: "handoff", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: Customer has seen our capability and objections are addressed", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: Economic buyer is aligned", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: Engagement structure agreed (pilot vs. full)", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: Solutions has the Discovery Report and is ready to design", priority: "exit_gate", condition_key: "" },
                ],
            },
        ],
    },

    // ── Phase B: Build It ────────────────────────────────────────────────────────
    TemplatePhase {
        id: "phase-b",
        phase_number: 2,
        title: "Phase B — Build It",
        color: "#2563EB",
        description: "Design the right solution, price it, write the contract, close. Solutions leads design; Capture leads the close.",
        tasks: &[
            TemplateTask {
                id: "b-4",
                title: "Stage 4 — Design Solution",
                gate: true,
                track_dates: false,
                has_equipment_picker: true,
                has_stakeholders: false,
                role_tag: "solutions",
                stage_number: 4,
                subtasks: &[
                    TemplateSubtask { text: "Solution architecture defined — products (platform, sensors, docks), services (coverage model, SOC, maintenance), operational model", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "SLA framework defined — response times, uptime, coverage, reporting cadence", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Preliminary pricing check — does this design hit 20%+ margin? If not, adjust architecture now before going further", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Implementation timeline estimated — account for procurement lead times, regulatory timelines, staffing needs", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Bespoke: engage Solution Architect (Dean Pratt); define custom engineering scope; document integration architecture (VMS, access control, SIEM, APIs); get CFO margin review", priority: "p0", condition_key: "bespoke" },
                    TemplateSubtask { text: "Starter Program: scope 1–2 docks, single site, 60–90 day window; define success metrics for conversion to full contract", priority: "p0", condition_key: "starter" },
                    TemplateSubtask { text: "Standard bundle: select from Base/Mid/Elite tier; map customer requirements; identify add-ons needed", priority: "p1", condition_key: "!bespoke" },
                    TemplateSubtask { text: "Integration scope documented — VMS, access control, alarms, SIEM, dispatch; identify technical complexity level", priority: "p1", condition_key: "" },
                    TemplateSubtask { text: "Ops capacity check initiated — pilot availability? Equipment availability? Can we deliver on the customer's timeline?", priority: "p1", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: Solution architecture is defined and documented", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: Preliminary pricing check passed (20%+ margin achievable)", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: Solution Architect has reviewed and approved the bespoke approach", priority: "exit_gate", condition_key: "bespoke" },
                    TemplateSubtask { text: "EXIT GATE: Implementation timeline is realistic given known constraints", priority: "exit_gate", condition_key: "" },
                ],
            },
            TemplateTask {
                id: "b-5",
                title: "Stage 5 — Price, SOW & Approve",
                gate: true,
                track_dates: false,
                has_equipment_picker: false,
                has_stakeholders: false,
                role_tag: "solutions",
                stage_number: 5,
                subtasks: &[
                    TemplateSubtask { text: "Pricing built — from Layer 1 catalog + Layer 2 bundles; apply tier discounts (5/10/15%); calculate all-in monthly cost", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Ops validation — Tyler Bayne confirms: component costs accurate, operationally feasible, capacity available, delivery timeline achievable", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Finance validation — margin meets 20% floor; if not, stop and adjust design or escalate to CFO (Mike Egan)", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "SOW drafted — deliverables, SLAs, timeline, roles, payment terms, acceptance criteria", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Contract terms prepared — MSA: liability insurance ($5M+), data privacy, termination, warranty", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Internal approval obtained — Segment Lead reviews; Ops confirms capacity; CRM updated", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "CFO deal review (Mike Egan) — required if margin below 20%, deal >$500K, non-standard terms, or bespoke/Layer 3", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Gov/defense: legal review for NDAA, ITAR, procurement terms; procurement cycle may add 4–12 weeks", priority: "p1", condition_key: "govdef" },
                    TemplateSubtask { text: "Cash flow modeling — for hardware-heavy DaaS deals: model working capital impact; flag to Finance if cash impact exceeds threshold", priority: "p2", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: Pricing is built and internally validated (Ops + Finance)", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: SOW is drafted with all required terms", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: All required approvals obtained (CFO if needed, executive if >$500K, legal if non-standard)", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: CRM updated — 50–75% probability", priority: "exit_gate", condition_key: "" },
                ],
            },
            TemplateTask {
                id: "b-6",
                title: "Stage 6 — Propose & Close",
                gate: true,
                track_dates: false,
                has_equipment_picker: false,
                has_stakeholders: true,
                role_tag: "capture+solutions",
                stage_number: 6,
                subtasks: &[
                    TemplateSubtask { text: "Proposal presented — Capture + Solutions co-present; executive summary for C-suite; technical detail for IT/Security", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Objections handled — use references, case studies, competitive positioning; Capture owns price/terms, Solutions owns technical/SLA pushback", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Negotiation completed — track customer approval workflow; target redlines addressed within 1 week", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Contract executed — final signatures; CRM → Closed Won; billing setup initiated", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Kickoff meeting scheduled — with customer, Delivery, and Solutions", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "HANDOFF TO DELIVERY: signed SOW (scope, SLAs, timeline, payment terms)", priority: "handoff", condition_key: "" },
                    TemplateSubtask { text: "HANDOFF TO DELIVERY: customer contacts — who to call for technical, procurement, and executive issues", priority: "handoff", condition_key: "" },
                    TemplateSubtask { text: "HANDOFF TO DELIVERY: site details — physical locations, access requirements, infrastructure readiness", priority: "handoff", condition_key: "" },
                    TemplateSubtask { text: "HANDOFF TO DELIVERY: special conditions — verbal commitments or timeline promises not in the SOW", priority: "handoff", condition_key: "" },
                    TemplateSubtask { text: "HANDOFF TO DELIVERY: regulatory status — waiver status, licensing status, known timeline risks", priority: "handoff", condition_key: "" },
                    TemplateSubtask { text: "HANDOFF TO DELIVERY: customer expectations — what matters most; what are they worried about", priority: "handoff", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: Contract is signed", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: Handoff package is complete (all items above)", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: Kickoff meeting is scheduled with customer + Delivery + Solutions", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: CRM → Closed Won", priority: "exit_gate", condition_key: "" },
                ],
            },
        ],
    },

    // ── Phase C: Run It & Grow It ────────────────────────────────────────────────
    TemplatePhase {
        id: "phase-c",
        phase_number: 3,
        title: "Phase C — Run It & Grow It",
        color: "#16A34A",
        description: "Delivery owns implementation (7–10). Operations runs steady state (11). Capture returns for expansion (12).",
        tasks: &[
            TemplateTask {
                id: "c-7",
                title: "Stage 7 — Procure & Provision",
                gate: true,
                track_dates: true,
                has_equipment_picker: true,
                has_stakeholders: false,
                role_tag: "delivery",
                stage_number: 7,
                subtasks: &[
                    TemplateSubtask { text: "Customer kickoff meeting completed — align on timeline, roles, communication cadence, customer readiness requirements", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Delivery plan published — milestones, resource allocation, installation schedule, risk register", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Equipment ordered — per SOW hardware profile; vendor lead times confirmed and tracked", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "QA & provisioning — receive, inspect, configure, firmware update, stage for deployment", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "FAA waiver application filed — Eric Larson (Airspace) drives filing; Rob Robertson (Regulatory) owns operational narrative; TRACK WEEKLY — expect 4–24 weeks", priority: "p0", condition_key: "drones" },
                    TemplateSubtask { text: "NDAA/ITAR compliance prepared for government/defense customer", priority: "p0", condition_key: "govdef" },
                    TemplateSubtask { text: "Pilot workforce recruitment initiated — James Nguyen begins recruiting/assigning certified pilots (2–4+ week lead time)", priority: "p1", condition_key: "drones" },
                    TemplateSubtask { text: "State/local guard licensing initiated — business entity registration, guard cards, background checks (2–6 weeks by state)", priority: "p0", condition_key: "manned" },
                    TemplateSubtask { text: "Staffing initiated — post orders drafted, shift schedules designed, recruitment started", priority: "p0", condition_key: "manned" },
                    TemplateSubtask { text: "EXIT GATE: Equipment ordered and delivery timeline confirmed", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: Delivery plan published to customer and internal team", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: All regulatory applications filed with timelines tracked", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: Customer has confirmed their readiness (project sponsor, team, infrastructure)", priority: "exit_gate", condition_key: "" },
                ],
            },
            TemplateTask {
                id: "c-8",
                title: "Stage 8 — Deploy & Integrate",
                gate: true,
                track_dates: false,
                has_equipment_picker: false,
                has_stakeholders: false,
                role_tag: "delivery",
                stage_number: 8,
                subtasks: &[
                    TemplateSubtask { text: "Equipment installed — docks, network/firewall, LTE/power, sensors, payloads", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "System integration completed — VMS, access control, alarms, SOC, SIEM, dispatch (per SOW scope)", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "End-to-end testing passed — full system test including failover scenarios", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "SOPs created — flight ops, emergency procedures, incident response, maintenance, data handling", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Bespoke: Solution Architect (Dean Pratt) available for integration troubleshooting; custom integration testing protocols; third-party vendor coordination", priority: "p0", condition_key: "bespoke" },
                    TemplateSubtask { text: "EXIT GATE: All equipment installed and configured", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: All integrations tested and working", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: SOPs documented", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE (HARD — drone deals): FAA waiver approved, state licenses obtained, insurance on file, NDAA/ITAR documented — DO NOT proceed to Stage 9 until all regulatory approvals are confirmed", priority: "exit_gate", condition_key: "drones" },
                ],
            },
            TemplateTask {
                id: "c-9",
                title: "Stage 9 — Train & Test",
                gate: true,
                track_dates: false,
                has_equipment_picker: false,
                has_stakeholders: false,
                role_tag: "delivery",
                stage_number: 9,
                subtasks: &[
                    TemplateSubtask { text: "Customer training delivered — SOC personnel and security managers trained on system operation and monitoring (Jon Beal runs this)", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "User Acceptance Testing (UAT) — flight tests, SLA validation, integration testing; customer participates and signs off", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "SOPs and training materials delivered to customer", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "DxD operators certified per Training standards — Jon Beal owns certification standards", priority: "p0", condition_key: "drones" },
                    TemplateSubtask { text: "Pilots deployed — Pilot Workforce (James Nguyen) assigns certified pilots; staffing commitments confirmed", priority: "p0", condition_key: "drones" },
                    TemplateSubtask { text: "BVLOS-specific curriculum delivered within Training's framework (Rob Robertson)", priority: "p0", condition_key: "bvlos" },
                    TemplateSubtask { text: "Public sector/DFR: specialized workshop for police/fire chiefs and first responders (Jon Beal)", priority: "p1", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: All personnel trained and certified (customer and DxD)", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: UAT completed with documented results", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: Customer has signed off on system readiness", priority: "exit_gate", condition_key: "" },
                ],
            },
            TemplateTask {
                id: "c-10",
                title: "Stage 10 — Go-Live",
                gate: true,
                track_dates: false,
                has_equipment_picker: false,
                has_stakeholders: true,
                role_tag: "delivery",
                stage_number: 10,
                subtasks: &[
                    TemplateSubtask { text: "Final acceptance testing (FAT) — all criteria verified; punch list resolved", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Written customer acceptance — formal sign-off document obtained", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Billing activated — recurring billing begins per contract terms", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "HANDOFF TO OPERATIONS: complete system configuration documentation", priority: "handoff", condition_key: "" },
                    TemplateSubtask { text: "HANDOFF TO OPERATIONS: all SOPs (operations, maintenance, emergency, incident response)", priority: "handoff", condition_key: "" },
                    TemplateSubtask { text: "HANDOFF TO OPERATIONS: customer contacts and escalation paths", priority: "handoff", condition_key: "" },
                    TemplateSubtask { text: "HANDOFF TO OPERATIONS: known issues, workarounds, and 'watch out for this' notes", priority: "handoff", condition_key: "" },
                    TemplateSubtask { text: "HANDOFF TO OPERATIONS: maintenance schedule and hardware lifecycle dates", priority: "handoff", condition_key: "" },
                    TemplateSubtask { text: "HANDOFF TO OPERATIONS: SLA details and reporting requirements", priority: "handoff", condition_key: "" },
                    TemplateSubtask { text: "HANDOFF TO OPERATIONS: Operations team confirms readiness and signs off on acceptance", priority: "handoff", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: Customer has signed acceptance", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: Billing is activated", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: Operations has accepted the handoff package and signed off", priority: "exit_gate", condition_key: "" },
                    TemplateSubtask { text: "EXIT GATE: Solutions is established as ongoing customer concierge", priority: "exit_gate", condition_key: "" },
                ],
            },
            TemplateTask {
                id: "c-11",
                title: "Stage 11 — Operate & Optimize",
                gate: false,
                track_dates: false,
                has_equipment_picker: false,
                has_stakeholders: false,
                role_tag: "operations",
                stage_number: 11,
                subtasks: &[
                    TemplateSubtask { text: "Service delivered per SLA — monitoring, response, coverage hours as contracted (Remote drone ops: Jeff Ventrella; Robotic/field hardware: Tyler Bayne)", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Incidents managed — response, resolution, documentation, customer communication", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Monthly operational report delivered to customer", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "30-day health check — CSAT survey, KPI review, issue resolution (early warning system)", priority: "p1", condition_key: "" },
                    TemplateSubtask { text: "Quarterly Business Review (QBR) — Solutions concierge joins; review performance, ROI, customer satisfaction, expansion opportunities", priority: "p1", condition_key: "" },
                    TemplateSubtask { text: "Continuous optimization — patrol routes, false positive reduction, autonomy improvements", priority: "p1", condition_key: "" },
                    TemplateSubtask { text: "Maintenance and updates — scheduled inspections, firmware/software updates, hardware refresh planning", priority: "p1", condition_key: "" },
                    TemplateSubtask { text: "Surface expansion opportunities to Solutions — coverage gaps, site growth, contract sizing issues", priority: "p1", condition_key: "" },
                    TemplateSubtask { text: "Post-implementation margin reconciliation — 30 days post go-live, compare actual vs. quoted cost; if variance >10%, run a post-mortem", priority: "p2", condition_key: "" },
                    TemplateSubtask { text: "Annual performance summary — year-in-review for the customer with ROI analysis", priority: "p2", condition_key: "" },
                ],
            },
            TemplateTask {
                id: "c-12",
                title: "Stage 12 — Expand & Renew",
                gate: false,
                track_dates: false,
                has_equipment_picker: false,
                has_stakeholders: false,
                role_tag: "capture",
                stage_number: 12,
                subtasks: &[
                    TemplateSubtask { text: "Expansion opportunities identified — Solutions (concierge) + Ops surface these from QBRs, operational data, and customer conversations", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Renewal process started at 120 days before expiration — 120/90/60-day cadence; performance + ROI summary prepared", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "New capabilities/sites: loop back to Stage 2 (Discover) — new requirements need new discovery", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Starter Program → full contract: loop back to Stage 4 (Design) — redesign at scale using pilot performance data; Capture gathers pilot metrics, Solutions provides narrative", priority: "p0", condition_key: "starter" },
                    TemplateSubtask { text: "Simple add-ons (more docks, same site): loop back to Stage 7 (Procure) — design is already known", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "Renewal at same scope: stays in Stage 12 — renew and continue", priority: "p0", condition_key: "" },
                    TemplateSubtask { text: "NRR tracking — target >120% net revenue retention", priority: "p1", condition_key: "" },
                    TemplateSubtask { text: "Multi-year terms pursued — longer commitments improve predictability and reduce churn risk", priority: "p1", condition_key: "" },
                ],
            },
        ],
    },
];
