pub struct TemplateTask {
    pub id: &'static str,
    pub title: &'static str,
    pub subtasks: &'static [&'static str],
    pub gate: bool,
    pub track_dates: bool,
    pub has_equipment_picker: bool,
    pub has_stakeholders: bool,
}

pub struct TemplatePhase {
    pub id: &'static str,
    pub phase_number: i32,
    pub title: &'static str,
    pub color: &'static str,
    pub description: &'static str,
    pub tasks: &'static [TemplateTask],
}

pub fn get_template() -> &'static [TemplatePhase] {
    &TEMPLATE
}

static TEMPLATE: [TemplatePhase; 4] = [
    TemplatePhase {
        id: "phase-1",
        phase_number: 1,
        title: "Scoping & Solutions",
        color: "#EF4444",
        description: "Define customer needs, assess property, and architect the security solution.",
        tasks: &[
            TemplateTask {
                id: "1-1",
                title: "Customer Problem & Outcome Definition",
                gate: false, track_dates: false, has_equipment_picker: false, has_stakeholders: false,
                subtasks: &[
                    "Clarify customer's problem statement and desired security outcome",
                    "Confirm customer success criteria and acceptance criteria",
                    "Discuss lead times on hardware/software with sales lead for contractual timelines",
                ],
            },
            TemplateTask {
                id: "1-2",
                title: "Site Assessment & Security Analysis",
                gate: false, track_dates: false, has_equipment_picker: false, has_stakeholders: false,
                subtasks: &[
                    "Assess key site characteristics (size, scope, perimeter, area, boundaries)",
                    "Identify security gaps and existing risks",
                    "Evaluate airspace considerations (Class G vs. Controlled Airspace)",
                    "Document weather considerations for flight operations",
                    "Assess power availability and connectivity options at deployment sites",
                    "Identify site layout, infrastructure, and environmental hazards (towers, buildings, trees)",
                    "Confirm client will provide: power (110V acceptable), network (40 Mbps minimum), Ethernet connection",
                ],
            },
            TemplateTask {
                id: "1-3",
                title: "Airspace & Regulatory Evaluation",
                gate: true, track_dates: false, has_equipment_picker: false, has_stakeholders: false,
                subtasks: &[
                    "Conduct airspace evaluation and determine approval pathway",
                    "Class G Airspace = Proceed to operations planning",
                    "Controlled Airspace = Initiate FAA Site Approval request (expect 30-day processing)",
                    "Document approved altitude limits from site approval",
                    "Discuss regulatory lead times and FAA waiver status with client",
                ],
            },
            TemplateTask {
                id: "1-4",
                title: "Drone & Equipment Selection",
                gate: true, track_dates: false, has_equipment_picker: true, has_stakeholders: false,
                subtasks: &[],
            },
            TemplateTask {
                id: "1-5",
                title: "Coverage Architecture & SLA Definition",
                gate: false, track_dates: false, has_equipment_picker: false, has_stakeholders: false,
                subtasks: &[
                    "Define coverage model (Centralized, De-Centralized, Hybrid, Static, Dynamic)",
                    "Determine dock placement locations and response time projections",
                    "Document coverage zones and flight characteristics (altitude, noise, visual profile)",
                    "Define discretion/deterrence approach",
                    "Establish Response Time SLAs",
                    "Set System Uptime and Availability Targets",
                    "Document Redundancy Requirements",
                    "Define Support Escalation & Incident Management procedures",
                    "Establish Maintenance Windows",
                ],
            },
            TemplateTask {
                id: "1-6",
                title: "Integration & Regulatory Scope",
                gate: false, track_dates: false, has_equipment_picker: false, has_stakeholders: false,
                subtasks: &[
                    "Identify connectivity requirements to existing security systems",
                    "Plan integration with local police departments and emergency services",
                    "Establish FAA waiver status and airspace authorization pathway",
                    "Define data security, privacy controls, and retention policies",
                    "Clarify liability and insurance coverage responsibilities",
                    "Document compliance/regulatory requirements specific to client site",
                ],
            },
            TemplateTask {
                id: "1-7",
                title: "Proposal & Solution Documentation",
                gate: false, track_dates: false, has_equipment_picker: false, has_stakeholders: false,
                subtasks: &[
                    "Develop Proposed Solution and Coverage Architecture",
                    "Create Proposal Options/Bundles for client review",
                    "Document Equipment Stack specifications",
                    "Define Performance Commitments and Service Level Agreements (SLAs)",
                    "Include security and non-security use cases",
                    "Document surge coverage options for special events",
                    "Outline future expansion options",
                    "Provide case studies and proof of performance examples",
                    "Include Cost/ROI/Cost-Benefit Analysis",
                    "Create high-level implementation timeline",
                    "Document customer responsibilities and acceptance criteria",
                ],
            },
            TemplateTask {
                id: "1-8",
                title: "Contract & Resource Planning",
                gate: true, track_dates: false, has_equipment_picker: false, has_stakeholders: false,
                subtasks: &[
                    "Review contract and SOW for completeness and mission set",
                    "Resolve any discrepancies and request clarification",
                    "Validate deployment details and confirm resource readiness",
                    "Confirm SOC capacity for the project",
                    "If SOC capacity is limited — Tempe GSOC: Contact Jeff Ventrella",
                    "If SOC capacity is limited — Dallas RSOC: Contact Tyler Morris or James Nguyen",
                    "Schedule project planning and sync meeting with all DXD parties involved",
                    "Identify customer stakeholders and Points of Contact (POCs)",
                    "Schedule check-in meetings with stakeholders during project lifecycle",
                ],
            },
        ],
    },
    TemplatePhase {
        id: "phase-2",
        phase_number: 2,
        title: "Delivery",
        color: "#F87171",
        description: "Procure all hardware, software, and supporting equipment; prepare for site installation.",
        tasks: &[
            TemplateTask {
                id: "2-1",
                title: "Hardware Procurement",
                gate: false, track_dates: true, has_equipment_picker: false, has_stakeholders: false,
                subtasks: &[
                    "DJI Dock 3 w/ Matrice 4TD → Genpac (Jon Beal)",
                    "AVSS Parachute Recovery Systems → Genpac (Jon Beal)",
                    "DJI Spotlights (AL1) → Genpac (Jon Beal)",
                    "DJI Speakers (AS1) → Genpac (Jon Beal)",
                    "Sunflower Labs BeeHive w/ Thermal Payload → Kenton Matthaei (Sunflower)",
                    "Skydio X10 Dock with X10 Drone → Tyler Bayne (Skydio/Post-Sales)",
                    "Casia G (DAA) → Uavionix",
                    "DroneTag (DAA) → Genpac (Jon Beal)",
                    "Axis P3275-LVE Dome Camera (required by FAA waiver)",
                    "CCTV camera pole/mount",
                    "DJI D-RTK 3 Relay Fixed Deployment units",
                    "DJI Matrice 4D Series batteries",
                    "Annual Class 2 Dock Licenses",
                    "ProCare Maintenance subscriptions",
                    "Casia G-as-a-Service licenses (if applicable)",
                    "Alpha Z Licenses for advanced analytics",
                ],
            },
            TemplateTask {
                id: "2-2",
                title: "Shipping & Logistics",
                gate: false, track_dates: false, has_equipment_picker: false, has_stakeholders: false,
                subtasks: &[
                    "Coordinate shipping method with each vendor to project site",
                    "Confirm shipping address and primary contact for delivery",
                    "Schedule delivery coordination and confirm ETAs with Site POC",
                    "Confirm client will accept delivery and store hardware securely",
                    "Create equipment receiving checklist to validate completeness",
                    "Establish inventory tracking with serial numbers and warranties",
                ],
            },
            TemplateTask {
                id: "2-3",
                title: "Site Survey & Infrastructure Assessment",
                gate: true, track_dates: false, has_equipment_picker: false, has_stakeholders: false,
                subtasks: &[
                    "Conduct Initial Site Visit to understand deployment needs",
                    "Perform Location Mapping for dock placement and availability assessment",
                    "Identify environmental and structural hazards",
                    "Customer provides: Power to Dock (110V acceptable)",
                    "Customer provides: Network to Dock (Ethernet, min 40 Mbps, Starlink acceptable)",
                    "Confirm dock securing method (concrete pads, pavers, or platform)",
                    "Confirm pole/tower requirements for DAA equipment",
                    "Confirm customer completed all required infrastructure setup",
                    "Create Site Survey Document (required by FAA waiver)",
                ],
            },
            TemplateTask {
                id: "2-4",
                title: "Installation Planning & Coordination",
                gate: false, track_dates: false, has_equipment_picker: false, has_stakeholders: false,
                subtasks: &[
                    "Schedule Hardware Installation Coordination",
                    "DJI Dock: DroneSense ($8,000) or DXD (if trained)",
                    "Sunflower BeeHive: Sunflower Labs installs",
                    "Skydio: Confirm installation provider",
                    "Casia G: Uavionix installs",
                    "DroneTag: DXD installs",
                    "Schedule all dock installations and training",
                    "Schedule Casia G Installation and training",
                    "Establish field maintenance program for drone assets",
                ],
            },
            TemplateTask {
                id: "2-5",
                title: "Perimeter Security & Compliance",
                gate: true, track_dates: false, has_equipment_picker: false, has_stakeholders: false,
                subtasks: &[
                    "Install CCTV cameras at dock sites (required by FAA waiver)",
                    "Install 'Monitored by Deus X Defense Drones' signage (required by FAA waiver)",
                    "Verify all safety and compliance markings are in place",
                ],
            },
        ],
    },
    TemplatePhase {
        id: "phase-3",
        phase_number: 3,
        title: "Execution",
        color: "#DC2626",
        description: "Configure systems, conduct testing, and transition to live operations.",
        tasks: &[
            TemplateTask {
                id: "3-1",
                title: "Command & Control (C2) System Setup",
                gate: false, track_dates: false, has_equipment_picker: false, has_stakeholders: false,
                subtasks: &[
                    "Draw automated patrol paths into C2 system",
                    "Verify patrol points align with customer requirements",
                    "Configure routine patrol times and schedules",
                    "Set Up Custom Reporting for customer dashboard",
                    "Add new users to customer dashboard for live monitoring",
                    "Set up distribution lists for report delivery",
                    "Configure piloting schedules in Belfry — Tempe GSOC: Jeff Ventrella",
                    "Configure piloting schedules in Belfry — Dallas RSOC: Tyler Morris or James Nguyen",
                ],
            },
            TemplateTask {
                id: "3-2",
                title: "Integration Testing & Validation",
                gate: false, track_dates: false, has_equipment_picker: false, has_stakeholders: false,
                subtasks: &[
                    "Conduct Real-World Application flight tests",
                    "Execute Fail-Safe Testing (power/internet loss simulation)",
                    "Verify drone reroutes and lands at Alternate Landing Site",
                    "Verify end-to-end data flow to command center and customer systems",
                    "Test alarm routing and customer notification workflows",
                    "Validate all integration points with customer's security systems",
                ],
            },
            TemplateTask {
                id: "3-3",
                title: "Customer Walkthrough & Documentation",
                gate: false, track_dates: false, has_equipment_picker: false, has_stakeholders: false,
                subtasks: &[
                    "Demonstrate automated drone deployment and launch sequence",
                    "Show live video feed from drone(s)",
                    "Walk through dashboard reporting and analytics",
                    "Review response protocols and escalation procedures",
                    "Provide customer with weekly inspection checklist (required by FAA waiver)",
                    "Document inspection and maintenance requirements",
                    "Deliver Service Documentation (SOPs, protocols, response times, procedures)",
                ],
            },
            TemplateTask {
                id: "3-4",
                title: "Safety & Compliance Validation",
                gate: false, track_dates: false, has_equipment_picker: false, has_stakeholders: false,
                subtasks: &[
                    "Conduct cybersecurity readiness review (all hardware/software)",
                    "Verify compliance with all FAA waiver requirements",
                    "Confirm all safety documentation is current and accessible",
                    "Validate operator training completion and certifications",
                    "Complete final cross-functional review of all operational requirements",
                ],
            },
            TemplateTask {
                id: "3-5",
                title: "Adjustments & Final Sign-Off",
                gate: true, track_dates: false, has_equipment_picker: false, has_stakeholders: false,
                subtasks: &[
                    "Make Final Revisions based on testing feedback",
                    "Obtain formal customer sign-off and acceptance",
                    "Conduct after-action review for process improvements",
                    "Finalize all documentation and compliance records",
                ],
            },
        ],
    },
    TemplatePhase {
        id: "phase-4",
        phase_number: 4,
        title: "Customer Success",
        color: "#B91C1C",
        description: "Transition to sustained operations, provide ongoing support, and optimize performance.",
        tasks: &[
            TemplateTask {
                id: "4-1",
                title: "Go-Live & Handover",
                gate: true, track_dates: false, has_equipment_picker: false, has_stakeholders: false,
                subtasks: &[
                    "Execute Go-Live Acceptance Checklist",
                    "Finalize Client Acceptance Checklist",
                    "Handover to Post-Sales team (Tyler Bayne or designated lead)",
                    "Document all as-built configurations and system settings",
                    "Provide customer with passwords and administrative access securely",
                ],
            },
            TemplateTask {
                id: "4-2",
                title: "Operational Support & Incident Response",
                gate: false, track_dates: false, has_equipment_picker: false, has_stakeholders: false,
                subtasks: &[
                    "Establish incident management processes and logging system",
                    "Document alarm response procedures",
                    "Document escalation protocols",
                    "Document law enforcement coordination procedures",
                    "Document emergency communication protocols",
                    "Implement equipment failure response SOP with vendor coordination",
                    "Develop asset downtime tracking process for service level monitoring",
                    "Create cyber incident response playbook",
                    "Document system failure playbooks (C2, VMS, network)",
                ],
            },
            TemplateTask {
                id: "4-3",
                title: "Maintenance & Vendor Coordination",
                gate: false, track_dates: false, has_equipment_picker: false, has_stakeholders: false,
                subtasks: &[
                    "Establish field maintenance program with operator guides",
                    "Document battery management and equipment rotation SOP",
                    "Create vendor escalation playbook for repairs and warranty claims",
                    "Finalize SLAs and support contracts with all vendors",
                    "Implement preventive maintenance schedule",
                    "Track equipment status, maintenance history, and warranties",
                ],
            },
            TemplateTask {
                id: "4-4",
                title: "Performance Monitoring & Optimization",
                gate: false, track_dates: false, has_equipment_picker: false, has_stakeholders: false,
                subtasks: &[
                    "Monitor system performance against established SLAs",
                    "Track response times and incident resolution metrics",
                    "Collect customer feedback on performance and user experience",
                    "Document lessons learned and improvement opportunities",
                    "Conduct quarterly performance reviews with customer",
                    "Identify expansion and upsell opportunities",
                ],
            },
            TemplateTask {
                id: "4-5",
                title: "Compliance & Documentation",
                gate: false, track_dates: false, has_equipment_picker: false, has_stakeholders: false,
                subtasks: &[
                    "Maintain current FAA waiver compliance documentation",
                    "Update insurance certificates as required",
                    "Conduct quarterly compliance audits against waiver requirements",
                    "Document all incidents and safety events for regulatory reporting",
                    "Maintain up-to-date emergency contact procedures",
                    "Ensure all operator certifications remain current (FAA Part 107)",
                ],
            },
            TemplateTask {
                id: "4-6",
                title: "Continuous Improvement & Team Training",
                gate: false, track_dates: false, has_equipment_picker: false, has_stakeholders: false,
                subtasks: &[
                    "Conduct operator recertification training annually",
                    "Hold quarterly safety and procedure refresher trainings",
                    "Run periodic live system drills (simulated incidents)",
                    "Update Standard Operating Procedures based on experience",
                    "Share best practices across RSOC teams",
                    "Conduct management training on new features and updates",
                ],
            },
        ],
    },
];
